### ISSUE TITLE
Acquire additional hardware

### ISSUE THREAD

**Issue by jMilesUC** [EECE3093C/team-project-big-boys#24]
Accessory cables, breadboards, etc.

**Comment by jMilesUC** [comment]
Breadboards, wire cutters, and other tools were provided by the 1819 Innovation Lab!  Parker had a spare micro USB-c to USB-a cable that he contributed.  Now we should have all the resources we need.

**Comment by rogersnj** [comment]
The innovation lab had all components necessary to complete this issue.
