### ISSUE TITLE
Determine pressure sensor choice for project

### ISSUE THREAD

**Issue by strbodj** [EECE3093C/team-project-big-boys#6]

**Comment by jMilesUC** [comment]
FORCE SENSING RESISTOR,1.5 INCH SQUARE,1oz-22LBS,2 LEADS,0.1 INCH SPACING
https://www.amazon.com/gp/product/B00B887DBC/ref=ppx_yo_dt_b_asin_title_o03_s00?ie=UTF8&psc=1
